# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'forms/breast_model.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(774, 783)
        Form.setStyleSheet("background-color: rgb(239, 243, 252);\n"
"font-family:Ubuntu;\n"
"font-size: 20px;\n"
"    color:black;\n"
"")
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.back_btn_2 = QtWidgets.QPushButton(Form)
        self.back_btn_2.setMinimumSize(QtCore.QSize(60, 60))
        self.back_btn_2.setMaximumSize(QtCore.QSize(60, 60))
        self.back_btn_2.setStyleSheet("QPushButton {\n"
"    background-color:rgba(6,103,184,255);\n"
"    color: #FFFFFF;\n"
"    padding: 2px;\n"
"    font: bold 15px;\n"
"    border-width: 6px;\n"
"    border-radius: 10px;\n"
"    border-color: #2752B8;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #827397;\n"
"}\n"
"QPushButton:pressed{\n"
"padding-left:5px;\n"
"padding-top:5px;\n"
"background-color:rgba(2, 65, 118, 100);\n"
"background-postion:calc(100% - 10px) center;}\n"
"")
        self.back_btn_2.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/ICONS/icons/back-button.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.back_btn_2.setIcon(icon)
        self.back_btn_2.setIconSize(QtCore.QSize(30, 30))
        self.back_btn_2.setFlat(True)
        self.back_btn_2.setObjectName("back_btn_2")
        self.gridLayout.addWidget(self.back_btn_2, 0, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(97, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 0, 1, 1, 1)
        self.label_25 = QtWidgets.QLabel(Form)
        self.label_25.setStyleSheet("background-color: rgb(85, 255, 127,0);\n"
"font-size:40px")
        self.label_25.setAlignment(QtCore.Qt.AlignCenter)
        self.label_25.setObjectName("label_25")
        self.gridLayout.addWidget(self.label_25, 0, 2, 1, 5)
        spacerItem1 = QtWidgets.QSpacerItem(18, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 0, 7, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem2, 1, 3, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem3, 2, 0, 1, 3)
        self.pickProfile_lbl = QtWidgets.QLabel(Form)
        self.pickProfile_lbl.setMinimumSize(QtCore.QSize(400, 500))
        self.pickProfile_lbl.setMaximumSize(QtCore.QSize(400, 500))
        self.pickProfile_lbl.setStyleSheet("  border-radius: 10px;\n"
" border: 2px solid     #dadada;\n"
"font-size:15px;\n"
"background-color: rgb(234, 237, 255,0);\n"
"\n"
"")
        self.pickProfile_lbl.setText("")
        self.pickProfile_lbl.setPixmap(QtGui.QPixmap(":/ICONS/icons/upload.png"))
        self.pickProfile_lbl.setScaledContents(False)
        self.pickProfile_lbl.setAlignment(QtCore.Qt.AlignCenter)
        self.pickProfile_lbl.setObjectName("pickProfile_lbl")
        self.gridLayout.addWidget(self.pickProfile_lbl, 2, 3, 1, 3)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem4, 2, 6, 1, 2)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem5, 3, 4, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(287, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem6, 4, 0, 1, 4)
        self.show_result_btn_3 = QtWidgets.QPushButton(Form)
        self.show_result_btn_3.setMinimumSize(QtCore.QSize(250, 50))
        self.show_result_btn_3.setMaximumSize(QtCore.QSize(330, 50))
        self.show_result_btn_3.setStyleSheet("QPushButton {\n"
"    background-color:rgba(6,103,184,255);\n"
"    color: #FFFFFF;\n"
"    padding: 2px;\n"
"    font: bold 15px;\n"
"    border-width: 6px;\n"
"    border-radius: 10px;\n"
"    border-color: #2752B8;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #827397;\n"
"}\n"
"QPushButton:pressed{\n"
"padding-left:5px;\n"
"padding-top:5px;\n"
"background-color:rgba(2, 65, 118, 100);\n"
"background-postion:calc(100% - 10px) center;}\n"
"")
        self.show_result_btn_3.setObjectName("show_result_btn_3")
        self.gridLayout.addWidget(self.show_result_btn_3, 4, 4, 1, 1)
        spacerItem7 = QtWidgets.QSpacerItem(201, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem7, 4, 5, 1, 3)
        spacerItem8 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem8, 5, 4, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_25.setText(_translate("Form", "BREAST CANCER CHECK"))
        self.show_result_btn_3.setText(_translate("Form", "Show result"))
import app_resources_rc
