# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'forms/change_password.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(827, 702)
        Form.setMinimumSize(QtCore.QSize(180, 40))
        Form.setStyleSheet("font-family:Ubuntu;\n"
"font-size: 20px;\n"
"background-color: rgb(239, 243, 252);")
        self.gridLayout_3 = QtWidgets.QGridLayout(Form)
        self.gridLayout_3.setObjectName("gridLayout_3")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem, 0, 1, 1, 1)
        self.groupBox_2 = QtWidgets.QGroupBox(Form)
        self.groupBox_2.setMinimumSize(QtCore.QSize(370, 600))
        self.groupBox_2.setMaximumSize(QtCore.QSize(400, 600))
        self.groupBox_2.setStyleSheet("QGroupBox{\n"
"    background-color: rgb(255, 255, 255);\n"
"\n"
"border-radius: 20% 20%;\n"
"color: white;\n"
"\n"
"\n"
";}\n"
"")
        self.groupBox_2.setTitle("")
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem1, 3, 0, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.cancel_btn = QtWidgets.QPushButton(self.groupBox_2)
        self.cancel_btn.setMinimumSize(QtCore.QSize(150, 40))
        self.cancel_btn.setMaximumSize(QtCore.QSize(110, 40))
        self.cancel_btn.setStyleSheet("QPushButton{\n"
"\n"
"\n"
"    background-color: rgb(255, 95, 86);\n"
"border-radius:20% 20%;\n"
"    border-color: rgb(0, 0, 0);\n"
"\n"
"\n"
"}\n"
"\n"
"\n"
"\n"
"QPushButton:pressed{\n"
"padding-left:5px;\n"
"padding-top:5px;\n"
"background-postion:calc(100% - 10px) center;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(255, 95, 86,.5);\n"
"\n"
"}")
        self.cancel_btn.setObjectName("cancel_btn")
        self.horizontalLayout_2.addWidget(self.cancel_btn)
        self.save_btn = QtWidgets.QPushButton(self.groupBox_2)
        self.save_btn.setMinimumSize(QtCore.QSize(150, 40))
        self.save_btn.setMaximumSize(QtCore.QSize(150, 40))
        self.save_btn.setStyleSheet("QPushButton{\n"
"\n"
"    background-color: rgb(56, 162, 255);\n"
"border-radius:20% 20%;\n"
"    border-color: rgb(0, 0, 0);\n"
"\n"
"\n"
"}\n"
"\n"
"\n"
"\n"
"QPushButton:pressed{\n"
"padding-left:5px;\n"
"padding-top:5px;\n"
"background-postion:calc(100% - 10px) center;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(56, 162, 255,.6);\n"
"\n"
"}")
        self.save_btn.setObjectName("save_btn")
        self.horizontalLayout_2.addWidget(self.save_btn)
        self.gridLayout_2.addLayout(self.horizontalLayout_2, 4, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.label = QtWidgets.QLabel(self.groupBox_2)
        self.label.setEnabled(True)
        self.label.setMinimumSize(QtCore.QSize(270, 220))
        self.label.setMaximumSize(QtCore.QSize(270, 220))
        self.label.setStyleSheet("background-color: rgb(156, 255, 247,0);")
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(":/ICONS/icons/Untitled-1.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem3)
        self.gridLayout_2.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem4, 1, 0, 1, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.olb_password_lin = QtWidgets.QLineEdit(self.groupBox_2)
        self.olb_password_lin.setMinimumSize(QtCore.QSize(350, 60))
        self.olb_password_lin.setMaximumSize(QtCore.QSize(350, 60))
        self.olb_password_lin.setStyleSheet("border: 2px solid #bebebe ;\n"
"border-radius: 10% 10%;\n"
"padding-left:5px;\n"
"background-color: rgb(255, 255, 255);\n"
"color: rgb(18, 32, 62);")
        self.olb_password_lin.setText("")
        self.olb_password_lin.setCursorMoveStyle(QtCore.Qt.VisualMoveStyle)
        self.olb_password_lin.setClearButtonEnabled(True)
        self.olb_password_lin.setObjectName("olb_password_lin")
        self.verticalLayout.addWidget(self.olb_password_lin)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem5)
        self.new_password_lin = QtWidgets.QLineEdit(self.groupBox_2)
        self.new_password_lin.setMinimumSize(QtCore.QSize(350, 60))
        self.new_password_lin.setMaximumSize(QtCore.QSize(350, 60))
        self.new_password_lin.setStyleSheet("border: 2px solid #bebebe ;\n"
"border-radius: 10% 10%;\n"
"padding-left:5px;\n"
"background-color: rgb(255, 255, 255);\n"
"color: rgb(18, 32, 62);")
        self.new_password_lin.setText("")
        self.new_password_lin.setCursorMoveStyle(QtCore.Qt.VisualMoveStyle)
        self.new_password_lin.setClearButtonEnabled(True)
        self.new_password_lin.setObjectName("new_password_lin")
        self.verticalLayout.addWidget(self.new_password_lin)
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem6)
        self.check_password_lin = QtWidgets.QLineEdit(self.groupBox_2)
        self.check_password_lin.setMinimumSize(QtCore.QSize(350, 60))
        self.check_password_lin.setMaximumSize(QtCore.QSize(350, 60))
        self.check_password_lin.setStyleSheet("border: 2px solid #bebebe ;\n"
"border-radius: 10% 10%;\n"
"padding-left:5px;\n"
"background-color: rgb(255, 255, 255);\n"
"color: rgb(18, 32, 62);")
        self.check_password_lin.setText("")
        self.check_password_lin.setCursorMoveStyle(QtCore.Qt.VisualMoveStyle)
        self.check_password_lin.setClearButtonEnabled(True)
        self.check_password_lin.setObjectName("check_password_lin")
        self.verticalLayout.addWidget(self.check_password_lin)
        self.gridLayout_2.addLayout(self.verticalLayout, 2, 0, 1, 1)
        spacerItem7 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem7, 5, 0, 1, 1)
        self.gridLayout_3.addWidget(self.groupBox_2, 1, 2, 1, 1)
        spacerItem8 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem8, 0, 2, 1, 1)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem9, 1, 3, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(Form)
        self.groupBox.setMinimumSize(QtCore.QSize(105, 0))
        self.groupBox.setMaximumSize(QtCore.QSize(105, 16777215))
        self.groupBox.setStyleSheet("QGroupBox{\n"
"    background-color: rgb(255, 255, 255);\n"
"\n"
"border-radius: 20% 20%;\n"
"color: white;\n"
"  box-shadow: 5px 10px;\n"
"\n"
";}")
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName("gridLayout")
        spacerItem10 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem10, 0, 0, 1, 1)
        self.change_password_btn = QtWidgets.QPushButton(self.groupBox)
        self.change_password_btn.setMinimumSize(QtCore.QSize(80, 80))
        self.change_password_btn.setStyleSheet("QPushButton{\n"
"    background-color: rgb(56, 163, 255);\n"
"border-radius:15% 15%;\n"
"    border-color: rgb(0, 0, 0);\n"
"\n"
"\n"
"\n"
"\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"padding-left:5px;\n"
"padding-top:5px;\n"
"background-postion:calc(100% - 10px) center;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:1, x2:1, y2:0, stop:0 rgba(3, 67, 165,.5), stop:1 rgba(12, 148, 207,.1));}")
        self.change_password_btn.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/ICONS/icons/password.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.change_password_btn.setIcon(icon)
        self.change_password_btn.setIconSize(QtCore.QSize(40, 40))
        self.change_password_btn.setFlat(True)
        self.change_password_btn.setObjectName("change_password_btn")
        self.gridLayout.addWidget(self.change_password_btn, 6, 0, 1, 1)
        spacerItem11 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout.addItem(spacerItem11, 3, 0, 1, 1)
        spacerItem12 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout.addItem(spacerItem12, 5, 0, 1, 1)
        spacerItem13 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem13, 7, 0, 1, 1)
        self.user_btn = QtWidgets.QPushButton(self.groupBox)
        self.user_btn.setMinimumSize(QtCore.QSize(80, 80))
        self.user_btn.setStyleSheet("QPushButton{\n"
"background-color: rgb(255, 255, 255,0);\n"
"border-radius:15% 15%;\n"
"    border-color: rgb(0, 0, 0);\n"
"\n"
"\n"
"\n"
"border: 2px solid #bebebe ;\n"
"    background-color: rgb(214, 214, 214);\n"
"  background-color: white;\n"
"  color: black;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"padding-left:5px;\n"
"padding-top:5px;\n"
"background-postion:calc(100% - 10px) center;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(255, 95, 86,.5);}\n"
"")
        self.user_btn.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/ICONS/icons/22.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.user_btn.setIcon(icon1)
        self.user_btn.setIconSize(QtCore.QSize(40, 40))
        self.user_btn.setFlat(True)
        self.user_btn.setObjectName("user_btn")
        self.gridLayout.addWidget(self.user_btn, 4, 0, 1, 1)
        self.home_btn = QtWidgets.QPushButton(self.groupBox)
        self.home_btn.setMinimumSize(QtCore.QSize(80, 80))
        self.home_btn.setMaximumSize(QtCore.QSize(80, 80))
        self.home_btn.setStyleSheet("QPushButton{\n"
"background-color: rgb(255, 255, 255,0);\n"
"border-radius:15% 15%;\n"
"    border-color: rgb(0, 0, 0);\n"
"\n"
"\n"
"\n"
"border: 2px solid #bebebe ;\n"
"    background-color: rgb(214, 214, 214);\n"
"  background-color: white;\n"
"  color: black;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"padding-left:5px;\n"
"padding-top:5px;\n"
"background-postion:calc(100% - 10px) center;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(226, 120, 255,.5);}")
        self.home_btn.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/ICONS/icons/home.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.home_btn.setIcon(icon2)
        self.home_btn.setIconSize(QtCore.QSize(50, 50))
        self.home_btn.setFlat(True)
        self.home_btn.setObjectName("home_btn")
        self.gridLayout.addWidget(self.home_btn, 2, 0, 1, 1)
        self.gridLayout_3.addWidget(self.groupBox, 0, 0, 3, 1)
        spacerItem14 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem14, 2, 2, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.cancel_btn.setText(_translate("Form", "Cancel"))
        self.save_btn.setText(_translate("Form", "Save"))
        self.olb_password_lin.setPlaceholderText(_translate("Form", "Old-Password"))
        self.new_password_lin.setPlaceholderText(_translate("Form", "New Password"))
        self.check_password_lin.setPlaceholderText(_translate("Form", "Re-Enter New Password"))
import app_resources_rc
