# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'forms/main_view.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1251, 664)
        Form.setStyleSheet("font-family:Ubuntu;\n"
"font-size: 20px;\n"
"background-color: rgb(239, 243, 252);")
        self.gridLayout_2 = QtWidgets.QGridLayout(Form)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.groupBox_2 = QtWidgets.QGroupBox(Form)
        self.groupBox_2.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius:20% 20%;\n"
"    border-top-color: rgb(0, 0, 0);\n"
"")
        self.groupBox_2.setTitle("")
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.diabetes_btn = QtWidgets.QPushButton(self.groupBox_2)
        self.diabetes_btn.setMinimumSize(QtCore.QSize(240, 210))
        self.diabetes_btn.setMaximumSize(QtCore.QSize(240, 210))
        self.diabetes_btn.setStyleSheet("QPushButton{\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:1, x2:1, y2:0, stop:0 rgba(3, 67, 165, 255), stop:1 rgba(12, 148, 207, 255));\n"
"\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"padding-left:5px;\n"
"padding-top:5px;\n"
"background-color:rgba(2, 65, 118, 100);\n"
"background-postion:calc(100% - 10px) center;\n"
"\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(181, 181, 181);\n"
"border-radius:20% 20%;\n"
"    border-color: rgb(0, 0, 0);\n"
"\n"
"}")
        self.diabetes_btn.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/ICONS/icons/diabetes text.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.diabetes_btn.setIcon(icon)
        self.diabetes_btn.setIconSize(QtCore.QSize(160, 160))
        self.diabetes_btn.setFlat(False)
        self.diabetes_btn.setObjectName("diabetes_btn")
        self.gridLayout_3.addWidget(self.diabetes_btn, 3, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem, 1, 6, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem1, 1, 2, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem2, 2, 1, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem3, 4, 1, 1, 1)
        self.parkinson_btn = QtWidgets.QPushButton(self.groupBox_2)
        self.parkinson_btn.setMinimumSize(QtCore.QSize(240, 210))
        self.parkinson_btn.setMaximumSize(QtCore.QSize(240, 210))
        self.parkinson_btn.setStyleSheet("QPushButton{\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:1, x2:1, y2:0, stop:0 rgba(3, 67, 165, 255), stop:1 rgba(12, 148, 207, 255));\n"
"\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"padding-left:5px;\n"
"padding-top:5px;\n"
"background-color:rgba(2, 65, 118, 100);\n"
"background-postion:calc(100% - 10px) center;\n"
"\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(181, 181, 181);\n"
"border-radius:20% 20%;\n"
"    border-color: rgb(0, 0, 0);\n"
"\n"
"}")
        self.parkinson_btn.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/ICONS/icons/parkinson text.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.parkinson_btn.setIcon(icon1)
        self.parkinson_btn.setIconSize(QtCore.QSize(150, 150))
        self.parkinson_btn.setFlat(False)
        self.parkinson_btn.setObjectName("parkinson_btn")
        self.gridLayout_3.addWidget(self.parkinson_btn, 3, 5, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem4, 0, 3, 1, 1)
        self.breast_btn = QtWidgets.QPushButton(self.groupBox_2)
        self.breast_btn.setMinimumSize(QtCore.QSize(240, 210))
        self.breast_btn.setMaximumSize(QtCore.QSize(240, 210))
        self.breast_btn.setStyleSheet("QPushButton{\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:1, x2:1, y2:0, stop:0 rgba(3, 67, 165, 255), stop:1 rgba(12, 148, 207, 255));\n"
"\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"padding-left:5px;\n"
"padding-top:5px;\n"
"background-color:rgba(2, 65, 118, 100);\n"
"background-postion:calc(100% - 10px) center;\n"
"\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(181, 181, 181);\n"
"border-radius:20% 20%;\n"
"    border-color: rgb(0, 0, 0);\n"
"\n"
"}")
        self.breast_btn.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/ICONS/icons/breast cancer text.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.breast_btn.setIcon(icon2)
        self.breast_btn.setIconSize(QtCore.QSize(150, 150))
        self.breast_btn.setFlat(False)
        self.breast_btn.setObjectName("breast_btn")
        self.gridLayout_3.addWidget(self.breast_btn, 1, 5, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem5, 1, 0, 1, 1)
        self.heart_btn = QtWidgets.QPushButton(self.groupBox_2)
        self.heart_btn.setMinimumSize(QtCore.QSize(240, 210))
        self.heart_btn.setMaximumSize(QtCore.QSize(240, 210))
        self.heart_btn.setStyleSheet("QPushButton{\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:1, x2:1, y2:0, stop:0 rgba(3, 67, 165, 255), stop:1 rgba(12, 148, 207, 255));\n"
"\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"padding-left:5px;\n"
"padding-top:5px;\n"
"background-color:rgba(2, 65, 118, 100);\n"
"background-postion:calc(100% - 10px) center;\n"
"\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(181, 181, 181);\n"
"border-radius:20% 20%;\n"
"    border-color: rgb(0, 0, 0);\n"
"\n"
"}")
        self.heart_btn.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/ICONS/icons/heart text.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.heart_btn.setIcon(icon3)
        self.heart_btn.setIconSize(QtCore.QSize(150, 150))
        self.heart_btn.setFlat(False)
        self.heart_btn.setObjectName("heart_btn")
        self.gridLayout_3.addWidget(self.heart_btn, 1, 3, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem6, 3, 0, 1, 1)
        spacerItem7 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem7, 2, 5, 1, 1)
        spacerItem8 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem8, 4, 3, 1, 1)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem9, 3, 6, 1, 1)
        self.brain_cancer_btn = QtWidgets.QPushButton(self.groupBox_2)
        self.brain_cancer_btn.setMinimumSize(QtCore.QSize(240, 210))
        self.brain_cancer_btn.setMaximumSize(QtCore.QSize(240, 210))
        self.brain_cancer_btn.setStyleSheet("QPushButton{\n"
"    border-top-color: rgb(0, 0, 0);\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:1, x2:1, y2:0, stop:0 rgba(3, 67, 165, 255), stop:1 rgba(12, 148, 207, 255));\n"
"\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"padding-left:5px;\n"
"padding-top:5px;\n"
"background-color:rgba(2, 65, 118, 100);\n"
"background-postion:calc(100% - 10px) center;\n"
"\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(181, 181, 181);\n"
"border-radius:20% 20%;\n"
"    border-color: rgb(0, 0, 0);\n"
"\n"
"}")
        self.brain_cancer_btn.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/ICONS/icons/brain text.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.brain_cancer_btn.setIcon(icon4)
        self.brain_cancer_btn.setIconSize(QtCore.QSize(150, 150))
        self.brain_cancer_btn.setFlat(False)
        self.brain_cancer_btn.setObjectName("brain_cancer_btn")
        self.gridLayout_3.addWidget(self.brain_cancer_btn, 1, 1, 1, 1)
        spacerItem10 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem10, 0, 1, 1, 1)
        self.blood_btn = QtWidgets.QPushButton(self.groupBox_2)
        self.blood_btn.setMinimumSize(QtCore.QSize(240, 210))
        self.blood_btn.setMaximumSize(QtCore.QSize(240, 210))
        self.blood_btn.setStyleSheet("QPushButton{\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:1, x2:1, y2:0, stop:0 rgba(3, 67, 165, 255), stop:1 rgba(12, 148, 207, 255));\n"
"\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"padding-left:5px;\n"
"padding-top:5px;\n"
"background-color:rgba(2, 65, 118, 100);\n"
"background-postion:calc(100% - 10px) center;\n"
"\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(181, 181, 181);\n"
"border-radius:20% 20%;\n"
"    border-color: rgb(0, 0, 0);\n"
"\n"
"}")
        self.blood_btn.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/ICONS/icons/blood with text.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.blood_btn.setIcon(icon5)
        self.blood_btn.setIconSize(QtCore.QSize(150, 150))
        self.blood_btn.setFlat(False)
        self.blood_btn.setObjectName("blood_btn")
        self.gridLayout_3.addWidget(self.blood_btn, 3, 3, 1, 1)
        spacerItem11 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem11, 4, 5, 1, 1)
        spacerItem12 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem12, 2, 3, 1, 1)
        spacerItem13 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem13, 3, 2, 1, 1)
        spacerItem14 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem14, 0, 5, 1, 1)
        spacerItem15 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem15, 1, 4, 1, 1)
        spacerItem16 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem16, 3, 4, 1, 1)
        self.gridLayout_2.addWidget(self.groupBox_2, 0, 2, 1, 1)
        spacerItem17 = QtWidgets.QSpacerItem(20, 693, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem17, 0, 1, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(Form)
        self.groupBox.setMinimumSize(QtCore.QSize(105, 0))
        self.groupBox.setMaximumSize(QtCore.QSize(105, 16777215))
        self.groupBox.setStyleSheet("QGroupBox{\n"
"    background-color: rgb(255, 255, 255);\n"
"\n"
"border-radius: 20% 20%;\n"
"color: white;\n"
"  box-shadow: 5px 10px;\n"
"\n"
";}")
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.user_btn = QtWidgets.QPushButton(self.groupBox)
        self.user_btn.setMinimumSize(QtCore.QSize(80, 80))
        self.user_btn.setStyleSheet("QPushButton{\n"
"background-color: rgb(255, 255, 255,0);\n"
"border-radius:15% 15%;\n"
"    border-color: rgb(0, 0, 0);\n"
"\n"
"\n"
"\n"
"border: 2px solid #bebebe ;\n"
"    background-color: rgb(214, 214, 214);\n"
"  background-color: white;\n"
"  color: black;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"padding-left:5px;\n"
"padding-top:5px;\n"
"background-postion:calc(100% - 10px) center;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(255, 95, 86,.5);}\n"
"")
        self.user_btn.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/ICONS/icons/22.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.user_btn.setIcon(icon6)
        self.user_btn.setIconSize(QtCore.QSize(40, 40))
        self.user_btn.setFlat(True)
        self.user_btn.setObjectName("user_btn")
        self.gridLayout.addWidget(self.user_btn, 5, 0, 1, 1)
        self.change_password_btn = QtWidgets.QPushButton(self.groupBox)
        self.change_password_btn.setMinimumSize(QtCore.QSize(80, 80))
        self.change_password_btn.setStyleSheet("QPushButton{\n"
"background-color: rgb(255, 255, 255,0);\n"
"border-radius:15% 15%;\n"
"    border-color: rgb(0, 0, 0);\n"
"\n"
"\n"
"\n"
"border: 2px solid #bebebe ;\n"
"    background-color: rgb(214, 214, 214);\n"
"  background-color: white;\n"
"  color: black;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"padding-left:5px;\n"
"padding-top:5px;\n"
"background-postion:calc(100% - 10px) center;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(255, 240, 76,.5);}")
        self.change_password_btn.setText("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/ICONS/icons/password.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.change_password_btn.setIcon(icon7)
        self.change_password_btn.setIconSize(QtCore.QSize(40, 40))
        self.change_password_btn.setFlat(True)
        self.change_password_btn.setObjectName("change_password_btn")
        self.gridLayout.addWidget(self.change_password_btn, 7, 0, 1, 1)
        spacerItem18 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout.addItem(spacerItem18, 6, 0, 1, 1)
        spacerItem19 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem19, 8, 0, 1, 1)
        spacerItem20 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem20, 0, 0, 1, 1)
        spacerItem21 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout.addItem(spacerItem21, 4, 0, 1, 1)
        self.home_btn = QtWidgets.QPushButton(self.groupBox)
        self.home_btn.setMinimumSize(QtCore.QSize(80, 80))
        self.home_btn.setMaximumSize(QtCore.QSize(80, 80))
        self.home_btn.setStyleSheet("QPushButton{\n"
"    background-color: rgb(56, 163, 255);\n"
"border-radius:15% 15%;\n"
"    border-color: rgb(0, 0, 0);\n"
"\n"
"\n"
"\n"
"\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"padding-left:5px;\n"
"padding-top:5px;\n"
"background-postion:calc(100% - 10px) center;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:1, x2:1, y2:0, stop:0 rgba(3, 67, 165,.5), stop:1 rgba(12, 148, 207,.1));}")
        self.home_btn.setText("")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/ICONS/icons/home.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.home_btn.setIcon(icon8)
        self.home_btn.setIconSize(QtCore.QSize(50, 50))
        self.home_btn.setFlat(True)
        self.home_btn.setObjectName("home_btn")
        self.gridLayout.addWidget(self.home_btn, 3, 0, 1, 1)
        self.results_btn = QtWidgets.QPushButton(self.groupBox)
        self.results_btn.setMinimumSize(QtCore.QSize(80, 80))
        self.results_btn.setMaximumSize(QtCore.QSize(80, 80))
        self.results_btn.setStyleSheet("QPushButton{\n"
"background-color: rgb(255, 255, 255,0);\n"
"border-radius:15% 15%;\n"
"    border-color: rgb(0, 0, 0);\n"
"\n"
"\n"
"\n"
"border: 2px solid #bebebe ;\n"
"    background-color: rgb(214, 214, 214);\n"
"  background-color: white;\n"
"  color: black;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"padding-left:5px;\n"
"padding-top:5px;\n"
"background-postion:calc(100% - 10px) center;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:1, x2:1, y2:0, stop:0 rgba(3, 67, 165,.5), stop:1 rgba(12, 148, 207,.1));}")
        self.results_btn.setText("")
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/ICONS/icons/2 (1).png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.results_btn.setIcon(icon9)
        self.results_btn.setIconSize(QtCore.QSize(40, 40))
        self.results_btn.setFlat(True)
        self.results_btn.setObjectName("results_btn")
        self.gridLayout.addWidget(self.results_btn, 1, 0, 1, 1)
        spacerItem22 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout.addItem(spacerItem22, 2, 0, 1, 1)
        self.gridLayout_2.addWidget(self.groupBox, 0, 0, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
import app_resources_rc
