# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'forms/profileClientedit_view.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1029, 884)
        Form.setStyleSheet("\n"
"background-color: rgb(239, 243, 252);\n"
"font-family:Ubuntu;\n"
"font-size: 20px;")
        self.gridLayout_4 = QtWidgets.QGridLayout(Form)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.groupBox_2 = QtWidgets.QGroupBox(Form)
        self.groupBox_2.setMinimumSize(QtCore.QSize(600, 0))
        self.groupBox_2.setMaximumSize(QtCore.QSize(600, 4567890))
        self.groupBox_2.setStyleSheet("QGroupBox{\n"
"    background-color: rgb(255, 255, 255);\n"
"\n"
"border-radius: 20% 20%;\n"
"color: white;\n"
"\n"
"\n"
";}\n"
"")
        self.groupBox_2.setTitle("")
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        spacerItem = QtWidgets.QSpacerItem(106, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem, 0, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.groupBox_3 = QtWidgets.QGroupBox(self.groupBox_2)
        self.groupBox_3.setMinimumSize(QtCore.QSize(220, 260))
        self.groupBox_3.setMaximumSize(QtCore.QSize(220, 260))
        self.groupBox_3.setStyleSheet("QGroupBox{\n"
"    background-color: rgb(255, 255, 255);\n"
"\n"
"border-radius: 20% 20%;\n"
"color: white;\n"
"\n"
"\n"
";}\n"
"\n"
"")
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.groupBox_3)
        self.label.setMinimumSize(QtCore.QSize(200, 200))
        self.label.setMaximumSize(QtCore.QSize(200, 200))
        self.label.setStyleSheet("border-radius:100% 100%;\n"
"border: 2px solid #bebebe ;\n"
"")
        self.label.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label.setText("")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.label_2 = QtWidgets.QLabel(self.groupBox_3)
        self.label_2.setMinimumSize(QtCore.QSize(0, 33))
        self.label_2.setMaximumSize(QtCore.QSize(390, 33))
        self.label_2.setStyleSheet("color:rgb(57,57,57,255);\n"
"background-color: rgb(255, 255, 255,0);")
        self.label_2.setText("")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.gridLayout_3.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.horizontalLayout.addWidget(self.groupBox_3)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.gridLayout_2.addLayout(self.horizontalLayout, 0, 1, 2, 1)
        spacerItem3 = QtWidgets.QSpacerItem(106, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem3, 1, 2, 1, 1)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.firstname_lin = QtWidgets.QLineEdit(self.groupBox_2)
        self.firstname_lin.setMinimumSize(QtCore.QSize(350, 60))
        self.firstname_lin.setMaximumSize(QtCore.QSize(350, 60))
        self.firstname_lin.setStyleSheet("border-radius:20% 20%;\n"
"border: 2px solid #bebebe ;\n"
"background-color:rgb(249,250,252,255);\n"
"padding-left:8px;\n"
"")
        self.firstname_lin.setText("")
        self.firstname_lin.setCursorMoveStyle(QtCore.Qt.VisualMoveStyle)
        self.firstname_lin.setClearButtonEnabled(True)
        self.firstname_lin.setObjectName("firstname_lin")
        self.verticalLayout_2.addWidget(self.firstname_lin)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem4)
        self.lastname_lin = QtWidgets.QLineEdit(self.groupBox_2)
        self.lastname_lin.setMinimumSize(QtCore.QSize(350, 60))
        self.lastname_lin.setMaximumSize(QtCore.QSize(350, 60))
        self.lastname_lin.setStyleSheet("border-radius:20% 20%;\n"
"border: 2px solid #bebebe ;\n"
"background-color:rgb(249,250,252,255);\n"
"padding-left:8px;\n"
"")
        self.lastname_lin.setCursorMoveStyle(QtCore.Qt.VisualMoveStyle)
        self.lastname_lin.setClearButtonEnabled(True)
        self.lastname_lin.setObjectName("lastname_lin")
        self.verticalLayout_2.addWidget(self.lastname_lin)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem5)
        self.email_lin = QtWidgets.QLineEdit(self.groupBox_2)
        self.email_lin.setMinimumSize(QtCore.QSize(350, 60))
        self.email_lin.setMaximumSize(QtCore.QSize(350, 60))
        self.email_lin.setStyleSheet("border-radius:20% 20%;\n"
"border: 2px solid #bebebe ;\n"
"background-color:rgb(249,250,252,255);\n"
"padding-left:8px;\n"
"")
        self.email_lin.setCursorMoveStyle(QtCore.Qt.VisualMoveStyle)
        self.email_lin.setClearButtonEnabled(True)
        self.email_lin.setObjectName("email_lin")
        self.verticalLayout_2.addWidget(self.email_lin)
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem6)
        self.gender_lin = QtWidgets.QLineEdit(self.groupBox_2)
        self.gender_lin.setMinimumSize(QtCore.QSize(350, 60))
        self.gender_lin.setMaximumSize(QtCore.QSize(350, 60))
        self.gender_lin.setStyleSheet("border-radius:20% 20%;\n"
"border: 2px solid #bebebe ;\n"
"background-color:rgb(249,250,252,255);\n"
"padding-left:8px;\n"
"line-shadow: 0 8px 16px 0 rgba(0,0,0,0.2), 0 6px 20px 0 rgba(0,0,0,0.19);\n"
"")
        self.gender_lin.setCursorMoveStyle(QtCore.Qt.VisualMoveStyle)
        self.gender_lin.setClearButtonEnabled(True)
        self.gender_lin.setObjectName("gender_lin")
        self.verticalLayout_2.addWidget(self.gender_lin)
        spacerItem7 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem7)
        self.userdoctor_lin = QtWidgets.QLineEdit(self.groupBox_2)
        self.userdoctor_lin.setMinimumSize(QtCore.QSize(350, 60))
        self.userdoctor_lin.setMaximumSize(QtCore.QSize(350, 60))
        self.userdoctor_lin.setStyleSheet("border-radius:20% 20%;\n"
"border: 2px solid #bebebe ;\n"
"background-color:rgb(249,250,252,255);\n"
"padding-left:8px;")
        self.userdoctor_lin.setObjectName("userdoctor_lin")
        self.verticalLayout_2.addWidget(self.userdoctor_lin)
        spacerItem8 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem8)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.cancel_btn = QtWidgets.QPushButton(self.groupBox_2)
        self.cancel_btn.setMinimumSize(QtCore.QSize(150, 40))
        self.cancel_btn.setMaximumSize(QtCore.QSize(110, 40))
        self.cancel_btn.setStyleSheet("QPushButton{\n"
"\n"
"\n"
"    background-color: rgb(255, 95, 86);\n"
"border-radius:20% 20%;\n"
"    border-color: rgb(0, 0, 0);\n"
"\n"
"\n"
"}\n"
"\n"
"\n"
"\n"
"QPushButton:pressed{\n"
"padding-left:5px;\n"
"padding-top:5px;\n"
"background-postion:calc(100% - 10px) center;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(255, 95, 86,.5);\n"
"\n"
"}")
        self.cancel_btn.setObjectName("cancel_btn")
        self.horizontalLayout_2.addWidget(self.cancel_btn)
        self.save_btn = QtWidgets.QPushButton(self.groupBox_2)
        self.save_btn.setMinimumSize(QtCore.QSize(150, 40))
        self.save_btn.setMaximumSize(QtCore.QSize(150, 40))
        self.save_btn.setStyleSheet("QPushButton{\n"
"\n"
"    background-color: rgb(56, 162, 255);\n"
"border-radius:20% 20%;\n"
"    border-color: rgb(0, 0, 0);\n"
"\n"
"\n"
"}\n"
"\n"
"\n"
"\n"
"QPushButton:pressed{\n"
"padding-left:5px;\n"
"padding-top:5px;\n"
"background-postion:calc(100% - 10px) center;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(56, 162, 255,.6);\n"
"\n"
"}")
        self.save_btn.setObjectName("save_btn")
        self.horizontalLayout_2.addWidget(self.save_btn)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.gridLayout_2.addLayout(self.verticalLayout_2, 2, 1, 1, 1)
        spacerItem9 = QtWidgets.QSpacerItem(106, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem9, 2, 2, 1, 1)
        spacerItem10 = QtWidgets.QSpacerItem(106, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem10, 2, 0, 1, 1)
        spacerItem11 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem11, 3, 1, 1, 1)
        self.gridLayout_4.addWidget(self.groupBox_2, 1, 2, 1, 1)
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setMinimumSize(QtCore.QSize(250, 35))
        self.label_3.setMaximumSize(QtCore.QSize(250, 35))
        self.label_3.setStyleSheet("font-size:40px;")
        self.label_3.setObjectName("label_3")
        self.gridLayout_4.addWidget(self.label_3, 0, 1, 1, 1)
        spacerItem12 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_4.addItem(spacerItem12, 2, 2, 1, 1)
        spacerItem13 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem13, 1, 1, 1, 1)
        spacerItem14 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem14, 1, 3, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(Form)
        self.groupBox.setMinimumSize(QtCore.QSize(105, 0))
        self.groupBox.setMaximumSize(QtCore.QSize(105, 16777215))
        self.groupBox.setStyleSheet("QGroupBox{\n"
"    background-color: rgb(255, 255, 255);\n"
"\n"
"border-radius: 20% 20%;\n"
"color: white;\n"
"  box-shadow: 5px 10px;\n"
"\n"
";}")
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName("gridLayout")
        spacerItem15 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem15, 1, 0, 1, 1)
        self.change_password_btn = QtWidgets.QPushButton(self.groupBox)
        self.change_password_btn.setMinimumSize(QtCore.QSize(80, 80))
        self.change_password_btn.setStyleSheet("QPushButton{\n"
"background-color: rgb(255, 255, 255,0);\n"
"border-radius:15% 15%;\n"
"    border-color: rgb(0, 0, 0);\n"
"\n"
"\n"
"\n"
"border: 2px solid #bebebe ;\n"
"    background-color: rgb(214, 214, 214);\n"
"  background-color: white;\n"
"  color: black;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"padding-left:5px;\n"
"padding-top:5px;\n"
"background-postion:calc(100% - 10px) center;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:1, x2:1, y2:0, stop:0 rgba(3, 67, 165,.5), stop:1 rgba(12, 148, 207,.1));}")
        self.change_password_btn.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/ICONS/icons/password.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.change_password_btn.setIcon(icon)
        self.change_password_btn.setIconSize(QtCore.QSize(40, 40))
        self.change_password_btn.setFlat(True)
        self.change_password_btn.setObjectName("change_password_btn")
        self.gridLayout.addWidget(self.change_password_btn, 7, 0, 1, 2)
        self.user_btn = QtWidgets.QPushButton(self.groupBox)
        self.user_btn.setMinimumSize(QtCore.QSize(80, 80))
        self.user_btn.setStyleSheet("QPushButton{\n"
"    background-color: rgb(56, 163, 255);\n"
"border-radius:15% 15%;\n"
"    border-color: rgb(0, 0, 0);\n"
"\n"
"\n"
"\n"
"\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"padding-left:5px;\n"
"padding-top:5px;\n"
"background-postion:calc(100% - 10px) center;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:1, x2:1, y2:0, stop:0 rgba(3, 67, 165,.5), stop:1 rgba(12, 148, 207,.1));}")
        self.user_btn.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/ICONS/icons/22.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.user_btn.setIcon(icon1)
        self.user_btn.setIconSize(QtCore.QSize(40, 40))
        self.user_btn.setFlat(True)
        self.user_btn.setObjectName("user_btn")
        self.gridLayout.addWidget(self.user_btn, 5, 0, 1, 2)
        spacerItem16 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem16, 8, 0, 1, 1)
        spacerItem17 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout.addItem(spacerItem17, 3, 0, 1, 1)
        self.logout_btn = QtWidgets.QPushButton(self.groupBox)
        self.logout_btn.setMinimumSize(QtCore.QSize(80, 80))
        self.logout_btn.setMaximumSize(QtCore.QSize(80, 80))
        self.logout_btn.setStyleSheet("QPushButton{\n"
"border-radius:15% 15%;\n"
"    background-color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"padding-left:5px;\n"
"padding-top:5px;\n"
"background-postion:calc(100% - 10px) center;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(255, 0, 0,.5);}\n"
"")
        self.logout_btn.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/ICONS/icons/log-out.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.logout_btn.setIcon(icon2)
        self.logout_btn.setIconSize(QtCore.QSize(60, 60))
        self.logout_btn.setFlat(True)
        self.logout_btn.setObjectName("logout_btn")
        self.gridLayout.addWidget(self.logout_btn, 0, 0, 1, 2)
        spacerItem18 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout.addItem(spacerItem18, 6, 0, 1, 1)
        self.home_btn = QtWidgets.QPushButton(self.groupBox)
        self.home_btn.setMinimumSize(QtCore.QSize(80, 80))
        self.home_btn.setMaximumSize(QtCore.QSize(80, 80))
        self.home_btn.setStyleSheet("QPushButton{\n"
"background-color: rgb(255, 255, 255,0);\n"
"border-radius:15% 15%;\n"
"    border-color: rgb(0, 0, 0);\n"
"\n"
"\n"
"\n"
"border: 2px solid #bebebe ;\n"
"    background-color: rgb(214, 214, 214);\n"
"  background-color: white;\n"
"  color: black;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"padding-left:5px;\n"
"padding-top:5px;\n"
"background-postion:calc(100% - 10px) center;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(226, 120, 255,.5);}")
        self.home_btn.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/ICONS/icons/home.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.home_btn.setIcon(icon3)
        self.home_btn.setIconSize(QtCore.QSize(50, 50))
        self.home_btn.setFlat(True)
        self.home_btn.setObjectName("home_btn")
        self.gridLayout.addWidget(self.home_btn, 2, 0, 1, 2)
        self.gridLayout_4.addWidget(self.groupBox, 0, 0, 3, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.groupBox_3.setTitle(_translate("Form", "GroupBox"))
        self.firstname_lin.setPlaceholderText(_translate("Form", "First-Name"))
        self.lastname_lin.setPlaceholderText(_translate("Form", "Last-Name"))
        self.email_lin.setPlaceholderText(_translate("Form", "Email"))
        self.gender_lin.setPlaceholderText(_translate("Form", "Gender"))
        self.userdoctor_lin.setPlaceholderText(_translate("Form", "User / Doctor"))
        self.cancel_btn.setText(_translate("Form", "Cancel"))
        self.save_btn.setText(_translate("Form", "Save"))
        self.label_3.setText(_translate("Form", "Client Profile"))
import app_resources_rc
