# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'forms/register_view.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1192, 766)
        Form.setStyleSheet("font-family:Ubuntu;\n"
"font-size: 20px;")
        self.gridLayout_7 = QtWidgets.QGridLayout(Form)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.widget = QtWidgets.QWidget(Form)
        self.widget.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:1, x2:1, y2:0, stop:0 rgba(3, 67, 165, 255), stop:1 rgba(12, 148, 207, 255));")
        self.widget.setObjectName("widget")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.widget)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.groupBox = QtWidgets.QGroupBox(self.widget)
        self.groupBox.setStyleSheet("border-style: outset;\n"
" border-color:transparent;\n"
"background-color:transparent;")
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_9.setObjectName("gridLayout_9")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_9.addItem(spacerItem, 2, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(100, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_9.addItem(spacerItem1, 0, 1, 1, 1)
        self.coach_btn = QtWidgets.QPushButton(self.groupBox)
        self.coach_btn.setEnabled(True)
        self.coach_btn.setMaximumSize(QtCore.QSize(16777215, 1080))
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(-1)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.coach_btn.setFont(font)
        self.coach_btn.setTabletTracking(False)
        self.coach_btn.setFocusPolicy(QtCore.Qt.NoFocus)
        self.coach_btn.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.coach_btn.setAcceptDrops(False)
        self.coach_btn.setToolTip("")
        self.coach_btn.setToolTipDuration(-2)
        self.coach_btn.setStatusTip("")
        self.coach_btn.setStyleSheet("background-color: rgb(0, 0, 0,0\n"
");\n"
"    font-size:30px;\n"
"")
        self.coach_btn.setInputMethodHints(QtCore.Qt.ImhNone)
        self.coach_btn.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/ICONS/icons/LOGO.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.coach_btn.setIcon(icon)
        self.coach_btn.setIconSize(QtCore.QSize(512, 512))
        self.coach_btn.setAutoRepeat(False)
        self.coach_btn.setAutoExclusive(False)
        self.coach_btn.setAutoDefault(False)
        self.coach_btn.setDefault(False)
        self.coach_btn.setFlat(True)
        self.coach_btn.setObjectName("coach_btn")
        self.gridLayout_9.addWidget(self.coach_btn, 0, 0, 1, 1)
        self.gridLayout_8.addWidget(self.groupBox, 1, 1, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_8.addItem(spacerItem2, 0, 1, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_8.addItem(spacerItem3, 1, 0, 1, 1)
        self.gridLayout_7.addWidget(self.widget, 0, 0, 1, 1)
        self.widget_2 = QtWidgets.QWidget(Form)
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.widget_2.setFont(font)
        self.widget_2.setStyleSheet("color: rgb(18, 32, 62);\n"
"background-color:rgb(239,243,252,255)")
        self.widget_2.setObjectName("widget_2")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.widget_2)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.gridLayout_5 = QtWidgets.QGridLayout()
        self.gridLayout_5.setObjectName("gridLayout_5")
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_5.addItem(spacerItem4, 1, 0, 1, 1)
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_5 = QtWidgets.QLabel(self.widget_2)
        self.label_5.setStyleSheet("color: rgb(171, 175, 183);")
        self.label_5.setObjectName("label_5")
        self.gridLayout_4.addWidget(self.label_5, 0, 0, 1, 1)
        self.password_check_lin = QtWidgets.QLineEdit(self.widget_2)
        self.password_check_lin.setMinimumSize(QtCore.QSize(350, 40))
        self.password_check_lin.setStyleSheet("font-family:arow;\n"
"background-color: rgb(255, 255, 255);\n"
"border-radius: 10% 10%;\n"
"font-size:15px;\n"
"padding-left:5px;\n"
"")
        self.password_check_lin.setEchoMode(QtWidgets.QLineEdit.Password)
        self.password_check_lin.setObjectName("password_check_lin")
        self.gridLayout_4.addWidget(self.password_check_lin, 1, 0, 1, 1)
        self.gridLayout_5.addLayout(self.gridLayout_4, 6, 0, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_5.addItem(spacerItem5, 3, 0, 1, 1)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label_2 = QtWidgets.QLabel(self.widget_2)
        self.label_2.setStyleSheet("color: rgb(171, 175, 183);")
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 1)
        self.email_lin = QtWidgets.QLineEdit(self.widget_2)
        self.email_lin.setMinimumSize(QtCore.QSize(350, 40))
        self.email_lin.setStyleSheet("font-family:arow;\n"
"background-color: rgb(255, 255, 255);\n"
"border-radius: 10% 10%;\n"
"font-size:15px;\n"
"padding-left:5px;\n"
"")
        self.email_lin.setInputMask("")
        self.email_lin.setText("")
        self.email_lin.setMaxLength(32767)
        self.email_lin.setFrame(False)
        self.email_lin.setPlaceholderText("")
        self.email_lin.setObjectName("email_lin")
        self.gridLayout.addWidget(self.email_lin, 1, 0, 1, 1)
        self.gridLayout_5.addLayout(self.gridLayout, 0, 0, 1, 1)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_3 = QtWidgets.QLabel(self.widget_2)
        self.label_3.setStyleSheet("color: rgb(171, 175, 183);")
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 0, 0, 1, 1)
        self.username_lin = QtWidgets.QLineEdit(self.widget_2)
        self.username_lin.setMinimumSize(QtCore.QSize(350, 40))
        self.username_lin.setStyleSheet("font-family:arow;\n"
"background-color: rgb(255, 255, 255);\n"
"border-radius: 10% 10%;\n"
"font-size:15px;\n"
"padding-left:5px;\n"
"")
        self.username_lin.setObjectName("username_lin")
        self.gridLayout_2.addWidget(self.username_lin, 1, 0, 1, 1)
        self.gridLayout_5.addLayout(self.gridLayout_2, 2, 0, 1, 1)
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.password_lin = QtWidgets.QLineEdit(self.widget_2)
        self.password_lin.setMinimumSize(QtCore.QSize(350, 40))
        self.password_lin.setStyleSheet("font-family:arow;\n"
"background-color: rgb(255, 255, 255);\n"
"border-radius: 10% 10%;\n"
"font-size:15px;\n"
"padding-left:5px;\n"
"")
        self.password_lin.setEchoMode(QtWidgets.QLineEdit.Password)
        self.password_lin.setObjectName("password_lin")
        self.gridLayout_3.addWidget(self.password_lin, 1, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.widget_2)
        self.label_4.setStyleSheet("color: rgb(171, 175, 183);")
        self.label_4.setObjectName("label_4")
        self.gridLayout_3.addWidget(self.label_4, 0, 0, 1, 1)
        self.gridLayout_5.addLayout(self.gridLayout_3, 4, 0, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_5.addItem(spacerItem6, 5, 0, 1, 1)
        self.gridLayout_6.addLayout(self.gridLayout_5, 4, 1, 1, 2)
        spacerItem7 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_6.addItem(spacerItem7, 3, 1, 1, 1)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_6.addItem(spacerItem8, 4, 3, 1, 1)
        spacerItem9 = QtWidgets.QSpacerItem(20, 80, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_6.addItem(spacerItem9, 5, 1, 1, 1)
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_6.addItem(spacerItem10, 4, 0, 1, 1)
        self.login_pushbutton = QtWidgets.QPushButton(self.widget_2)
        self.login_pushbutton.setMinimumSize(QtCore.QSize(150, 50))
        self.login_pushbutton.setMaximumSize(QtCore.QSize(150, 50))
        self.login_pushbutton.setStyleSheet("QPushButton {\n"
"    background-color:rgba(255,255,255,255);\n"
"    color: black;\n"
"    padding: 2px;\n"
"    font: bold 15px;\n"
"    border-width: 6px;\n"
"    border-radius: 10px;\n"
"    border-color: #2752B8;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #827397;\n"
"}\n"
"QPushButton:pressed{\n"
"padding-left:5px;\n"
"padding-top:5px;\n"
"background-color:rgba(2, 65, 118, 100);\n"
"background-postion:calc(100% - 10px) center;\n"
"}\n"
"")
        self.login_pushbutton.setObjectName("login_pushbutton")
        self.gridLayout_6.addWidget(self.login_pushbutton, 0, 2, 1, 1)
        spacerItem11 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_6.addItem(spacerItem11, 1, 2, 1, 1)
        self.label = QtWidgets.QLabel(self.widget_2)
        font = QtGui.QFont()
        font.setFamily("arow")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("font-family:arow;\n"
"font-size:30px;\n"
"color:rgb(18,32,62,255);")
        self.label.setObjectName("label")
        self.gridLayout_6.addWidget(self.label, 2, 1, 1, 1)
        self.gridLayout_7.addWidget(self.widget_2, 0, 1, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_5.setText(_translate("Form", "confirm password"))
        self.label_2.setText(_translate("Form", "Email"))
        self.label_3.setText(_translate("Form", "Username"))
        self.label_4.setText(_translate("Form", "Password"))
        self.login_pushbutton.setText(_translate("Form", "LOGIN"))
        self.label.setText(_translate("Form", "Register"))
import app_resources_rc
