# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'forms/register_view.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1279, 1272)
        Form.setStyleSheet("background-color: rgb(239, 243, 252);\n"
"color: rgb(18, 32, 62);\n"
"font-family:Ubuntu;\n"
"font-size: 20px;")
        self.gridLayout_47 = QtWidgets.QGridLayout(Form)
        self.gridLayout_47.setObjectName("gridLayout_47")
        self.groupBox_3 = QtWidgets.QGroupBox(Form)
        self.groupBox_3.setMinimumSize(QtCore.QSize(615, 692))
        self.groupBox_3.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:1, x2:1, y2:0, stop:0 rgba(3, 67, 165, 255), stop:1 rgba(12, 148, 207, 255));")
        self.groupBox_3.setTitle("")
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_7 = QtWidgets.QLabel(self.groupBox_3)
        self.label_7.setMinimumSize(QtCore.QSize(606, 605))
        self.label_7.setMaximumSize(QtCore.QSize(606, 605))
        self.label_7.setStyleSheet("background-color: rgb(255, 255, 255,0);")
        self.label_7.setText("")
        self.label_7.setPixmap(QtGui.QPixmap(":/ICONS/icons/LOGO.png"))
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.gridLayout_2.addWidget(self.label_7, 0, 0, 1, 1)
        self.gridLayout_47.addWidget(self.groupBox_3, 0, 0, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(Form)
        self.groupBox.setMinimumSize(QtCore.QSize(0, 0))
        self.groupBox.setMaximumSize(QtCore.QSize(720, 16777215))
        self.groupBox.setStyleSheet("color: rgb(18, 32, 62);\n"
"background-color:rgb(239,243,252,255)")
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_46 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_46.setObjectName("gridLayout_46")
        self.label_13 = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("arow")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.label_13.setFont(font)
        self.label_13.setStyleSheet("font-family:arow;\n"
"font-size:30px;\n"
"color:rgb(18,32,62,255);")
        self.label_13.setObjectName("label_13")
        self.gridLayout_46.addWidget(self.label_13, 0, 0, 1, 1)
        self.scrollArea = QtWidgets.QScrollArea(self.groupBox)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 599, 1169))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout_42 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout_42.setObjectName("gridLayout_42")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem)
        self.profile_picture_lbl_4 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.profile_picture_lbl_4.setMinimumSize(QtCore.QSize(130, 130))
        self.profile_picture_lbl_4.setMaximumSize(QtCore.QSize(130, 130))
        self.profile_picture_lbl_4.setStyleSheet("border-radius:30% 30%;\n"
"")
        self.profile_picture_lbl_4.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.profile_picture_lbl_4.setText("")
        self.profile_picture_lbl_4.setPixmap(QtGui.QPixmap(":/ICONS/icons/aaaaaa.png"))
        self.profile_picture_lbl_4.setScaledContents(True)
        self.profile_picture_lbl_4.setAlignment(QtCore.Qt.AlignCenter)
        self.profile_picture_lbl_4.setObjectName("profile_picture_lbl_4")
        self.horizontalLayout_8.addWidget(self.profile_picture_lbl_4)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem1)
        self.gridLayout_42.addLayout(self.horizontalLayout_8, 0, 0, 1, 2)
        self.gridLayout_35 = QtWidgets.QGridLayout()
        self.gridLayout_35.setObjectName("gridLayout_35")
        self.username_lin_4 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.username_lin_4.setMinimumSize(QtCore.QSize(350, 40))
        self.username_lin_4.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.username_lin_4.setStyleSheet("border-radius: 10% 10%;\n"
"padding-left:5px;\n"
"background-color: rgb(255, 255, 255);\n"
"color: rgb(18, 32, 62);")
        self.username_lin_4.setInputMask("")
        self.username_lin_4.setText("")
        self.username_lin_4.setMaxLength(32767)
        self.username_lin_4.setFrame(False)
        self.username_lin_4.setPlaceholderText("")
        self.username_lin_4.setObjectName("username_lin_4")
        self.gridLayout_35.addWidget(self.username_lin_4, 1, 0, 1, 1)
        self.label_44 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_44.setStyleSheet("color: rgb(171, 175, 183);")
        self.label_44.setObjectName("label_44")
        self.gridLayout_35.addWidget(self.label_44, 0, 0, 1, 1)
        self.gridLayout_42.addLayout(self.gridLayout_35, 1, 0, 1, 2)
        self.gridLayout_36 = QtWidgets.QGridLayout()
        self.gridLayout_36.setObjectName("gridLayout_36")
        self.label_45 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_45.setStyleSheet("color: rgb(171, 175, 183);")
        self.label_45.setObjectName("label_45")
        self.gridLayout_36.addWidget(self.label_45, 0, 0, 1, 1)
        self.first_name_lin_4 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.first_name_lin_4.setMinimumSize(QtCore.QSize(165, 40))
        self.first_name_lin_4.setMaximumSize(QtCore.QSize(9999999, 16777215))
        self.first_name_lin_4.setStyleSheet("border-radius: 10% 10%;\n"
"padding-left:5px;\n"
"background-color: rgb(255, 255, 255);\n"
"color: rgb(18, 32, 62);")
        self.first_name_lin_4.setInputMask("")
        self.first_name_lin_4.setText("")
        self.first_name_lin_4.setMaxLength(32767)
        self.first_name_lin_4.setFrame(False)
        self.first_name_lin_4.setPlaceholderText("")
        self.first_name_lin_4.setObjectName("first_name_lin_4")
        self.gridLayout_36.addWidget(self.first_name_lin_4, 1, 0, 1, 1)
        self.gridLayout_42.addLayout(self.gridLayout_36, 2, 0, 1, 1)
        self.gridLayout_37 = QtWidgets.QGridLayout()
        self.gridLayout_37.setObjectName("gridLayout_37")
        self.last_name_lin_4 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.last_name_lin_4.setMinimumSize(QtCore.QSize(165, 40))
        self.last_name_lin_4.setMaximumSize(QtCore.QSize(16777215, 9999999))
        self.last_name_lin_4.setStyleSheet("border-radius: 10% 10%;\n"
"padding-left:5px;\n"
"background-color: rgb(255, 255, 255);\n"
"color: rgb(18, 32, 62);")
        self.last_name_lin_4.setInputMask("")
        self.last_name_lin_4.setText("")
        self.last_name_lin_4.setMaxLength(32767)
        self.last_name_lin_4.setFrame(False)
        self.last_name_lin_4.setPlaceholderText("")
        self.last_name_lin_4.setObjectName("last_name_lin_4")
        self.gridLayout_37.addWidget(self.last_name_lin_4, 1, 0, 1, 1)
        self.label_46 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_46.setStyleSheet("color: rgb(171, 175, 183);")
        self.label_46.setObjectName("label_46")
        self.gridLayout_37.addWidget(self.label_46, 0, 0, 1, 1)
        self.gridLayout_42.addLayout(self.gridLayout_37, 2, 1, 1, 1)
        self.gridLayout_38 = QtWidgets.QGridLayout()
        self.gridLayout_38.setObjectName("gridLayout_38")
        self.label_47 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_47.setStyleSheet("color: rgb(171, 175, 183);")
        self.label_47.setObjectName("label_47")
        self.gridLayout_38.addWidget(self.label_47, 0, 0, 1, 1)
        self.name_lin_4 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.name_lin_4.setMinimumSize(QtCore.QSize(350, 40))
        self.name_lin_4.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.name_lin_4.setStyleSheet("border-radius: 10% 10%;\n"
"padding-left:5px;\n"
"background-color: rgb(255, 255, 255);\n"
"color: rgb(18, 32, 62);")
        self.name_lin_4.setInputMask("")
        self.name_lin_4.setText("")
        self.name_lin_4.setMaxLength(32767)
        self.name_lin_4.setFrame(False)
        self.name_lin_4.setPlaceholderText("")
        self.name_lin_4.setObjectName("name_lin_4")
        self.gridLayout_38.addWidget(self.name_lin_4, 1, 0, 1, 1)
        self.gridLayout_42.addLayout(self.gridLayout_38, 3, 0, 1, 2)
        self.gridLayout_39 = QtWidgets.QGridLayout()
        self.gridLayout_39.setObjectName("gridLayout_39")
        self.label_48 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_48.setStyleSheet("color: rgb(171, 175, 183);")
        self.label_48.setObjectName("label_48")
        self.gridLayout_39.addWidget(self.label_48, 0, 0, 1, 1)
        self.email_lin_4 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.email_lin_4.setMinimumSize(QtCore.QSize(350, 40))
        self.email_lin_4.setMaximumSize(QtCore.QSize(16777215, 9999999))
        self.email_lin_4.setStyleSheet("border-radius: 10% 10%;\n"
"padding-left:5px;\n"
"background-color: rgb(255, 255, 255);\n"
"color: rgb(18, 32, 62);")
        self.email_lin_4.setInputMask("")
        self.email_lin_4.setText("")
        self.email_lin_4.setMaxLength(32767)
        self.email_lin_4.setFrame(False)
        self.email_lin_4.setPlaceholderText("")
        self.email_lin_4.setObjectName("email_lin_4")
        self.gridLayout_39.addWidget(self.email_lin_4, 1, 0, 1, 1)
        self.gridLayout_42.addLayout(self.gridLayout_39, 4, 0, 1, 2)
        self.gridLayout_40 = QtWidgets.QGridLayout()
        self.gridLayout_40.setObjectName("gridLayout_40")
        self.bio_lin_4 = QtWidgets.QTextEdit(self.scrollAreaWidgetContents)
        self.bio_lin_4.setMinimumSize(QtCore.QSize(350, 80))
        self.bio_lin_4.setMaximumSize(QtCore.QSize(16777215, 9999999))
        self.bio_lin_4.setStyleSheet("border-radius: 10% 10%;\n"
"padding-left:5px;\n"
"background-color: rgb(255, 255, 255);\n"
"color: rgb(18, 32, 62);")
        self.bio_lin_4.setObjectName("bio_lin_4")
        self.gridLayout_40.addWidget(self.bio_lin_4, 1, 0, 1, 1)
        self.label_49 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_49.setMinimumSize(QtCore.QSize(0, 30))
        self.label_49.setMaximumSize(QtCore.QSize(16777215, 10))
        self.label_49.setStyleSheet("color: rgb(171, 175, 183);")
        self.label_49.setObjectName("label_49")
        self.gridLayout_40.addWidget(self.label_49, 0, 0, 1, 1)
        self.gridLayout_42.addLayout(self.gridLayout_40, 5, 0, 1, 2)
        self.gridLayout_41 = QtWidgets.QGridLayout()
        self.gridLayout_41.setObjectName("gridLayout_41")
        self.phone_number_lin_4 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.phone_number_lin_4.setMinimumSize(QtCore.QSize(350, 40))
        self.phone_number_lin_4.setMaximumSize(QtCore.QSize(16777215, 9999999))
        self.phone_number_lin_4.setStyleSheet("border-radius: 10% 10%;\n"
"padding-left:5px;\n"
"background-color: rgb(255, 255, 255);\n"
"color: rgb(18, 32, 62);")
        self.phone_number_lin_4.setInputMask("")
        self.phone_number_lin_4.setText("")
        self.phone_number_lin_4.setMaxLength(32767)
        self.phone_number_lin_4.setFrame(False)
        self.phone_number_lin_4.setPlaceholderText("")
        self.phone_number_lin_4.setObjectName("phone_number_lin_4")
        self.gridLayout_41.addWidget(self.phone_number_lin_4, 1, 0, 1, 1)
        self.label_50 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_50.setStyleSheet("color: rgb(171, 175, 183);")
        self.label_50.setObjectName("label_50")
        self.gridLayout_41.addWidget(self.label_50, 0, 0, 1, 1)
        self.gridLayout_42.addLayout(self.gridLayout_41, 6, 0, 1, 2)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_51 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_51.setStyleSheet("color: rgb(171, 175, 183);")
        self.label_51.setObjectName("label_51")
        self.horizontalLayout_9.addWidget(self.label_51)
        self.age_sb_4 = QtWidgets.QSpinBox(self.scrollAreaWidgetContents)
        self.age_sb_4.setStyleSheet("  height: 32px;\n"
"  border-radius: 4px;\n"
"\n"
" border-color:white;\n"
"background-color:transparent;\n"
"\n"
"  border: 1px solid #ffffff;\n"
"  position: relative;\n"
"  text-align: center;\n"
"  font-size: 20px;\n"
"  width: 80px;\n"
"  outline: none;\n"
"\n"
"  caret-color: transparent;;\n"
"\n"
"QLineEdit{\n"
"border: 1px solid #ABAFB7;\n"
"\n"
"}\n"
"QLineEdit:focus {\n"
"  border: 3px solid #ffff;\n"
"}\n"
"\n"
"\n"
"QLineEdit{\n"
"border: 1px solid #ABAFB7;\n"
"\n"
"}\n"
"QLineEdit:focus {\n"
"  border: 3px solid #555;\n"
"}\n"
"\n"
"")
        self.age_sb_4.setMaximum(130)
        self.age_sb_4.setObjectName("age_sb_4")
        self.horizontalLayout_9.addWidget(self.age_sb_4)
        self.horizontalLayout_10.addLayout(self.horizontalLayout_9)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_5 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_5.setMinimumSize(QtCore.QSize(0, 0))
        self.label_5.setStyleSheet("background-color: rgb(255, 255, 255,0);\n"
"color: rgb(171, 175, 183);\n"
"")
        self.label_5.setObjectName("label_5")
        self.horizontalLayout.addWidget(self.label_5)
        self.gander_combobox_4 = QtWidgets.QComboBox(self.scrollAreaWidgetContents)
        self.gander_combobox_4.setMinimumSize(QtCore.QSize(0, 0))
        self.gander_combobox_4.setMaximumSize(QtCore.QSize(150, 60))
        self.gander_combobox_4.setStyleSheet("background:transparent;\n"
"  border-radius: 20px;\n"
"color: rgb(171, 175, 183);\n"
"    ;\n"
" border: 2px solid  #ffffff;\n"
"padding:15px;\n"
"\n"
"")
        self.gander_combobox_4.setObjectName("gander_combobox_4")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icons/male.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.gander_combobox_4.addItem(icon, "")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/icons/female.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.gander_combobox_4.addItem(icon1, "")
        self.horizontalLayout.addWidget(self.gander_combobox_4)
        self.horizontalLayout_10.addLayout(self.horizontalLayout)
        self.gridLayout_42.addLayout(self.horizontalLayout_10, 7, 0, 1, 2)
        self.gridLayout_43 = QtWidgets.QGridLayout()
        self.gridLayout_43.setObjectName("gridLayout_43")
        self.password1_lin_4 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.password1_lin_4.setMinimumSize(QtCore.QSize(350, 40))
        self.password1_lin_4.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.password1_lin_4.setStyleSheet("border-radius: 10% 10%;\n"
"padding-left:5px;\n"
"background-color: rgb(255, 255, 255);\n"
"color: rgb(18, 32, 62);")
        self.password1_lin_4.setEchoMode(QtWidgets.QLineEdit.Password)
        self.password1_lin_4.setObjectName("password1_lin_4")
        self.gridLayout_43.addWidget(self.password1_lin_4, 1, 0, 1, 1)
        self.label_52 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_52.setStyleSheet("color: rgb(171, 175, 183);")
        self.label_52.setObjectName("label_52")
        self.gridLayout_43.addWidget(self.label_52, 0, 0, 1, 1)
        self.gridLayout_42.addLayout(self.gridLayout_43, 8, 0, 1, 2)
        self.gridLayout_44 = QtWidgets.QGridLayout()
        self.gridLayout_44.setObjectName("gridLayout_44")
        self.label_53 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_53.setStyleSheet("color: rgb(171, 175, 183);")
        self.label_53.setObjectName("label_53")
        self.gridLayout_44.addWidget(self.label_53, 0, 0, 1, 1)
        self.password2_lin_4 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.password2_lin_4.setMinimumSize(QtCore.QSize(350, 40))
        self.password2_lin_4.setMaximumSize(QtCore.QSize(16777215, 9999999))
        self.password2_lin_4.setStyleSheet("border-radius: 10% 10%;\n"
"padding-left:5px;\n"
"background-color: rgb(255, 255, 255);\n"
"color: rgb(18, 32, 62);")
        self.password2_lin_4.setEchoMode(QtWidgets.QLineEdit.Password)
        self.password2_lin_4.setObjectName("password2_lin_4")
        self.gridLayout_44.addWidget(self.password2_lin_4, 1, 0, 1, 1)
        self.gridLayout_49 = QtWidgets.QGridLayout()
        self.gridLayout_49.setObjectName("gridLayout_49")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_49.addItem(spacerItem2, 0, 2, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_49.addItem(spacerItem3, 0, 0, 1, 1)
        self.siginup_btn_4 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.siginup_btn_4.setMinimumSize(QtCore.QSize(221, 50))
        self.siginup_btn_4.setMaximumSize(QtCore.QSize(150, 50))
        self.siginup_btn_4.setStyleSheet("QPushButton {\n"
"    background-color:rgba(6,103,184,255);\n"
"    color: #FFFFFF;\n"
"    padding: 2px;\n"
"    font: bold 15px;\n"
"    border-width: 6px;\n"
"    border-radius: 10px;\n"
"    border-color: #2752B8;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #827397;\n"
"}")
        self.siginup_btn_4.setObjectName("siginup_btn_4")
        self.gridLayout_49.addWidget(self.siginup_btn_4, 0, 1, 1, 1)
        self.gridLayout_44.addLayout(self.gridLayout_49, 2, 0, 1, 1)
        self.gridLayout_42.addLayout(self.gridLayout_44, 9, 0, 1, 2)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout_46.addWidget(self.scrollArea, 1, 0, 1, 2)
        self.login_btn = QtWidgets.QPushButton(self.groupBox)
        self.login_btn.setMinimumSize(QtCore.QSize(150, 50))
        self.login_btn.setMaximumSize(QtCore.QSize(150, 50))
        self.login_btn.setStyleSheet("QPushButton {\n"
"    background-color:rgba(255,255,255,255);\n"
"    color: black;\n"
"    padding: 2px;\n"
"    font: bold 15px;\n"
"    border-width: 6px;\n"
"    border-radius: 10px;\n"
"    border-color: #2752B8;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #827397;\n"
"}\n"
"QPushButton:pressed{\n"
"padding-left:5px;\n"
"padding-top:5px;\n"
"background-color:rgba(2, 65, 118, 100);\n"
"background-postion:calc(100% - 10px) center;\n"
"}\n"
"")
        self.login_btn.setObjectName("login_btn")
        self.gridLayout_46.addWidget(self.login_btn, 0, 1, 1, 1)
        self.gridLayout_47.addWidget(self.groupBox, 0, 1, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_13.setText(_translate("Form", "Register"))
        self.label_44.setText(_translate("Form", "Username"))
        self.label_45.setText(_translate("Form", "First name"))
        self.label_46.setText(_translate("Form", "Last name"))
        self.label_47.setText(_translate("Form", "Name"))
        self.label_48.setText(_translate("Form", "Email"))
        self.label_49.setText(_translate("Form", "Bio"))
        self.label_50.setText(_translate("Form", "Phone-num"))
        self.label_51.setText(_translate("Form", "age"))
        self.label_5.setText(_translate("Form", "Gander"))
        self.gander_combobox_4.setItemText(0, _translate("Form", "Male"))
        self.gander_combobox_4.setItemText(1, _translate("Form", "Female"))
        self.label_52.setText(_translate("Form", "Password"))
        self.label_53.setText(_translate("Form", "confirm password"))
        self.siginup_btn_4.setText(_translate("Form", "SIGNUP"))
        self.login_btn.setText(_translate("Form", "LOGIN"))
import app_resources_rc
